export enum ActionType {
  ON_GUESTS_LOADED = 'ON_GUESTS_LOADED',
  UNLOAD_DATA = 'UNLOAD_DATA',
  ON_SAILINGS_LOADED = 'ON_SAILINGS_LOADED',
  CREATE_RESERVATION = 'CREATE_RESERVATION',
  CHANGE_RESERVATION = 'CHANGE_RESERVATION'
}
