export default `
<svg width="24px" height="24px" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1">
 <!-- Generated by Pixelmator Pro 1.1.5 -->
 <path id="path" d="M12 11 C13.66 11 14.99 9.66 14.99 8 14.99 6.34 13.66 5 12 5 10.34 5 9 6.34 9 8 9 9.66 10.34 11 12 11 Z M12 13 C9.67 13 5 14.17 5 16.5 L5 19 19 19 19 16.5 C19 14.17 14.33 13 12 13 Z" fill="#ffffff" fill-opacity="1" stroke="none"/>
</svg>`
